<a href="https://colab.research.google.com/github/fiedler-m/NLP_Sentiment_Analysis/blob/main/NLP_sentiment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns
import string
import nltk
import warnings 
warnings.filterwarnings("ignore", category=DeprecationWarning)
%matplotlib inline

In [2]:
train_data = pd.read_csv('https://github.com/fiedler-m/NLP_Sentiment_Analysis/blob/main/twitter_train_set.csv?raw=true')

In [3]:
train_data_og = train_data.copy()

In [4]:
train_data.shape

(31962, 3)

In [ ]:
train_data

In [6]:
test_data = pd.read_csv('https://github.com/fiedler-m/NLP_Sentiment_Analysis/blob/main/twitter_test_set.csv?raw=true')

In [7]:
test_data_og = test_data.copy()

In [8]:
test_data.shape

(17197, 2)

In [9]:
combine_data = train_data.append(test_data, ignore_index=True, sort=True)

In [10]:
combine_data.head()

id  label                                              tweet
0   1    0.0   @user when a father is dysfunctional and is s...
1   2    0.0  @user @user thanks for #lyft credit i can't us...
2   3    0.0                                bihday your majesty
3   4    0.0  #model   i love u take with u all the time in ...
4   5    0.0             factsguide: society now    #motivation

In [11]:
combine_data.tail()

id  label                                              tweet
49154  49155    NaN  thought factory: left-right polarisation! #tru...
49155  49156    NaN  feeling like a mermaid 😘 #hairflip #neverre...
49156  49157    NaN  #hillary #campaigned today in #ohio((omg)) &am...
49157  49158    NaN  happy, at work conference: right mindset leads...
49158  49159    NaN  my   song "so glad" free download!  #shoegaze ...

In [12]:
#preprocess data

def remove_p(text, pattern):
  r = re.findall(pattern, text)
  
  for i in r: 
    text = re.sub(i,"", text)
    
  return text

In [13]:
combine_data['Tweets_Cleaned'] = np.vectorize(remove_p)(combine_data['tweet'], "@[\w]*")
combine_data.head()

id  ...                                     Tweets_Cleaned
0   1  ...    when a father is dysfunctional and is so sel...
1   2  ...    thanks for #lyft credit i can't use cause th...
2   3  ...                                bihday your majesty
3   4  ...  #model   i love u take with u all the time in ...
4   5  ...             factsguide: society now    #motivation

[5 rows x 4 columns]

In [14]:
combine_data['Tweets_Cleaned'] = combine_data['Tweets_Cleaned'].str.replace("[^a-zA-Z#]", " ")
combine_data.head()

id  ...                                     Tweets_Cleaned
0   1  ...    when a father is dysfunctional and is so sel...
1   2  ...    thanks for #lyft credit i can t use cause th...
2   3  ...                                bihday your majesty
3   4  ...  #model   i love u take with u all the time in ...
4   5  ...             factsguide  society now    #motivation

[5 rows x 4 columns]

In [15]:
token_tweets = combine_data['Tweets_Cleaned'].apply(lambda x: x.split())
token_tweets.head()

0    [when, a, father, is, dysfunctional, and, is, ...
1    [thanks, for, #lyft, credit, i, can, t, use, c...
2                              [bihday, your, majesty]
3    [#model, i, love, u, take, with, u, all, the, ...
4              [factsguide, society, now, #motivation]
Name: Tweets_Cleaned, dtype: object

In [17]:
from nltk import PorterStemmer

port_stem = PorterStemmer()

token_tweets = token_tweets.apply(lambda x: [port_stem.stem(i) for i in x])
token_tweets.head()

0    [when, a, father, is, dysfunct, and, is, so, s...
1    [thank, for, #lyft, credit, i, can, t, use, ca...
2                              [bihday, your, majesti]
3    [#model, i, love, u, take, with, u, all, the, ...
4                    [factsguid, societi, now, #motiv]
Name: Tweets_Cleaned, dtype: object

In [18]:
for i in range(len(token_tweets)):
  token_tweets[i] = ' '.join(token_tweets[i])

combine_data['Tweets_Cleaned'] = token_tweets

In [19]:
def Hashtags_Extract(x):
    hashtags=[]
    
    # Loop over the words in the tweet
    for i in x:
        ht = re.findall(r'#(\w+)',i)
        hashtags.append(ht)
    
    return hashtags

In [20]:
hashtag_positive = Hashtags_Extract(combine_data['Tweets_Cleaned'][combine_data['label']==0])

In [21]:
hashtag_positive_unnest = sum(hashtag_positive,[])

In [22]:
hashtag_negative = Hashtags_Extract(combine_data['Tweets_Cleaned'][combine_data['label']==1])

In [23]:
hashtag_negative_unnest = sum(hashtag_negative,[])

In [ ]:
positive_word_freq = nltk.FreqDist(hashtag_positive_unnest)
positive_word_freq

In [25]:
df_positive = pd.DataFrame({'Hashtags':list(positive_word_freq.keys()), 'Count':list(positive_word_freq.values())})
df_positive.head()

Hashtags  Count
0        run     72
1       lyft      2
2  disapoint      1
3   getthank      2
4      model    375

In [ ]:
negative_word_freq = nltk.FreqDist(hashtag_negative_unnest)
negative_word_freq

In [28]:
df_negative = pd.DataFrame({'Hashtags':list(negative_word_freq.keys()),'Count':list(negative_word_freq.values())})
df_negative.head(10)

Hashtags  Count
0              cnn     10
1         michigan      2
2             tcot     14
3        australia      6
4     opkillingbay      5
5      seashepherd     22
6  helpcovedolphin      3
7           thecov      4
8         neverump      8
9       xenophobia     12

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

bag_vectorizer = CountVectorizer(max_df = 0.90, min_df=2, max_features=2000, stop_words='english')

bag_of_words = bag_vectorizer.fit_transform(combine_data['Tweets_Cleaned'])

df_bag = pd.DataFrame(bag_of_words.todense())
df_bag

In [114]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf=TfidfVectorizer(max_df=0.90, min_df=2,max_features=2000,stop_words='english')

tfidf_matrix=tfidf.fit_transform(combine_data['Tweets_Cleaned'])

df_tfidf = pd.DataFrame(tfidf_matrix.todense())

df_tfidf

0     1     2     3     4     5     ...  1994  1995  1996  1997  1998  1999
0       0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
1       0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
2       0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
3       0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
4       0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
...     ...   ...   ...   ...   ...   ...  ...   ...   ...   ...   ...   ...   ...
49154   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
49155   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
49156   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
49157   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0
49158   0.0   0.0   0.0   0.0   0.0   0.0  ...   0.0   0.0   0.0   0.0   0.0   0.0

[49159 rows x 2000 columns]

In [104]:
train_bag = bag_of_words[:31962]
train_bag.todense()

matrix([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        ...,
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]])

In [105]:
train_tfidf = tfidf_matrix[:31962]
train_tfidf.todense()

matrix([[0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.]])

In [106]:
from sklearn.model_selection import train_test_split

x_train_bag, x_validate_bag, y_train_bag, y_validate_bag = train_test_split(train_bag,train_data['label'],
                                                                                            test_size = 0.2, random_state=12)

x_train_tfidf, x_validate_tfidf, y_train_tfidf, y_validate_tfidf = train_test_split(train_tfidf,train_data['label'],
                                                                                            test_size = 0.2, random_state=30)


In [118]:
from sklearn.linear_model import LogisticRegression
log_reg_model = LogisticRegression(random_state=0, solver='lbfgs')

In [119]:
log_reg_model.fit(x_train_bag, y_train_bag)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [120]:
bag_prediction = log_reg_model.predict_proba(x_validate_bag)
bag_prediction

array([[0.99070641, 0.00929359],
       [0.92064642, 0.07935358],
       [0.99638225, 0.00361775],
       ...,
       [0.9978616 , 0.0021384 ],
       [0.99878348, 0.00121652],
       [0.78756384, 0.21243616]])

In [121]:
from sklearn.metrics import f1_score

prediction_int = bag_prediction[:,1]>=0.3
prediction_int = prediction_int.astype(np.int)
prediction_int

bag_score = f1_score(y_validate_bag, prediction_int)
bag_score

0.6502242152466368

In [122]:
log_reg_model.fit(x_train_tfidf, y_train_tfidf)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [123]:
tfidf_prediction = log_reg_model.predict_proba(x_validate_tfidf)
tfidf_prediction

array([[0.98750425, 0.01249575],
       [0.99400272, 0.00599728],
       [0.94920091, 0.05079909],
       ...,
       [0.96089488, 0.03910512],
       [0.94791722, 0.05208278],
       [0.96020469, 0.03979531]])

In [124]:
prediction_int = tfidf_prediction[:,1]>=0.3

prediction_int = prediction_int.astype(np.int)
prediction_int

# calculating f1 score
tfidf_score = f1_score(y_validate_tfidf, prediction_int)
tfidf_score

0.5755208333333333